name: Weekly Scheduled Workflow

on:
  schedule:
    # 매주 금요일 오후 12시에 실행
    - cron: "0 12 * * 5"

jobs:
  run-scheduled-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Set Environment Variables
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          OPEN_API_KEY: ${{ secrets.OPEN_API_KEY }}
        run: |
          echo "NOTION_API_KEY: $NOTION_API_KEY"
          echo "NOTION_DATABASE_ID: $NOTION_DATABASE_ID"
          echo "OPEN_API_KEY: $OPEN_API_KEY"

      - name: Run task
        run: echo "This action runs every Friday at 12:00 PM!"
